import Accordion from "../Accordion";

export default function PersonalRules() {
    const aboutFaq = [
        {
            title: "Can I change my email if I registered with the wrong one?",
            description:
                "Yes, send an email to help@saweria.co or DM us on Instagram/Twitter to change your registered email.",
        },
        {
            title: "I forgot my 2FA token, how do I retrive it?",
            description:
                "2FA tokens are automatically generated by Google Authenticator/Authy and change constantly. Do not delete the app while 2FA is active on Saweria.",
        },
        {
            title: "Can 2FA be disabled?",
            description:
                "Yes, contact via email or DM on Instagram/Twitter to disable 2FA.",
        },
    ];

    return (
        <>
            <h1 className="text-4xl">Pengaturan Data Diri</h1>
            <div className="grid grid-cols-1 md:grid-col-2 lg:grid-cols-3 gap-8 md:gap-8">
                {aboutFaq.map((faq, index) => (
                    <Accordion
                        key={index}
                        title={faq.title}
                        description={faq.description}
                    />
                ))}
            </div>
        </>
    );
}
